// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: merchants.sql

package db

import (
	"context"
	"database/sql"
)

const createMerchant = `-- name: CreateMerchant :one
insert into merchants (
   user_id,
   store_name,
   "description"
) values ( $1,
           $2,
           $3 ) returning "id",
                          user_id,
                          store_name,
                          "description",
                          created_at
`

type CreateMerchantParams struct {
	UserID      int32
	StoreName   string
	Description sql.NullString
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, createMerchant, arg.UserID, arg.StoreName, arg.Description)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreName,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getMerchantByUserID = `-- name: GetMerchantByUserID :one
select "id",
       user_id,
       store_name,
       "description",
       created_at
  from merchants
 where user_id = $1
`

func (q *Queries) GetMerchantByUserID(ctx context.Context, userID int32) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByUserID, userID)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreName,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getMerchantDashboard = `-- name: GetMerchantDashboard :one
select count(*) as total_products,
       coalesce(
          sum(stock),
          0
       ) as total_stock,
       coalesce(
          sum(price * stock),
          0
       ) as inventory_value,
       count(*) filter(where stock = 0) as out_of_stock
  from products
 where merchant_id = $1
`

type GetMerchantDashboardRow struct {
	TotalProducts  int64
	TotalStock     interface{}
	InventoryValue interface{}
	OutOfStock     int64
}

func (q *Queries) GetMerchantDashboard(ctx context.Context, merchantID int32) (GetMerchantDashboardRow, error) {
	row := q.db.QueryRowContext(ctx, getMerchantDashboard, merchantID)
	var i GetMerchantDashboardRow
	err := row.Scan(
		&i.TotalProducts,
		&i.TotalStock,
		&i.InventoryValue,
		&i.OutOfStock,
	)
	return i, err
}
