// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"
	"time"
)

const createOrder = `-- name: CreateOrder :one
insert into orders (customer_id, status, total)
values ($1, 'pending', $2)
returning id, customer_id, status, total, created_at
`

type CreateOrderParams struct {
	CustomerID int32
	Total      float64
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.CustomerID, arg.Total)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Status,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
insert into order_items (order_id, product_id, quantity, unit_price)
values ($1, $2, $3, $4)
returning id, order_id, product_id, quantity, unit_price
`

type CreateOrderItemParams struct {
	OrderID   int32
	ProductID int32
	Quantity  int32
	UnitPrice float64
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
	)
	return i, err
}

const deductStock = `-- name: DeductStock :one
update products
set stock = stock - $2
where id = $1
    and stock >= $2
returning stock
`

type DeductStockParams struct {
	ID    int32
	Stock int32
}

func (q *Queries) DeductStock(ctx context.Context, arg DeductStockParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, deductStock, arg.ID, arg.Stock)
	var stock int32
	err := row.Scan(&stock)
	return stock, err
}

const getCustomerOrders = `-- name: GetCustomerOrders :many
select o.id, o.customer_id, o.status, o.total, o.created_at,
    oi.product_id,
    oi.quantity,
    oi.unit_price
from orders o
    join order_items oi on oi.order_id = o.id
where o.customer_id = $1
order by o.created_at desc
`

type GetCustomerOrdersRow struct {
	ID         int32
	CustomerID int32
	Status     OrderStatus
	Total      float64
	CreatedAt  time.Time
	ProductID  int32
	Quantity   int32
	UnitPrice  float64
}

func (q *Queries) GetCustomerOrders(ctx context.Context, customerID int32) ([]GetCustomerOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, getCustomerOrders, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomerOrdersRow
	for rows.Next() {
		var i GetCustomerOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Status,
			&i.Total,
			&i.CreatedAt,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByID = `-- name: GetOrderByID :one
select id, customer_id, status, total, created_at
from orders
where id = $1 and customer_id = $2
`

type GetOrderByIDParams struct {
	ID         int32
	CustomerID int32
}

func (q *Queries) GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, arg.ID, arg.CustomerID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Status,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const getProductForUpdate = `-- name: GetProductForUpdate :one
select id,
    merchant_id,
    stock,
    price
from products
where id = $1 for
update
`

type GetProductForUpdateRow struct {
	ID         int32
	MerchantID int32
	Stock      int32
	Price      float64
}

func (q *Queries) GetProductForUpdate(ctx context.Context, id int32) (GetProductForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getProductForUpdate, id)
	var i GetProductForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Stock,
		&i.Price,
	)
	return i, err
}
