// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"
	"database/sql"
)

const createProduct = `-- name: CreateProduct :one
insert into products (
   merchant_id,
   "name",
   "description",
   price,
   stock
) values ( $1,
           $2,
           $3,
           $4,
           $5 ) returning "id",
                            merchant_id,
                            "name",
                            "description",
                            price,
                            stock,
                            created_at
`

type CreateProductParams struct {
	MerchantID  int32
	Name        string
	Description sql.NullString
	Price       float64
	Stock       int32
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.MerchantID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :execrows
delete from products
 where id = $1
   and merchant_id = $2
`

type DeleteProductParams struct {
	ID         int32
	MerchantID int32
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProduct, arg.ID, arg.MerchantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMerchantsProducts = `-- name: GetMerchantsProducts :many
select id, merchant_id, name, description, price, stock, created_at
  from products
 where merchant_id = $1
`

func (q *Queries) GetMerchantsProducts(ctx context.Context, merchantID int32) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getMerchantsProducts, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProduct = `-- name: GetProduct :one
select id, merchant_id, name, description, price, stock, created_at
  from products
 where id = $1
   and merchant_id = $2
`

type GetProductParams struct {
	ID         int32
	MerchantID int32
}

func (q *Queries) GetProduct(ctx context.Context, arg GetProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, arg.ID, arg.MerchantID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
update products
   set "name" = $3,
       "description" = $4,
       price = $5,
       stock = $6
 where "id" = $1
   and merchant_id = $2
returning "id",
             merchant_id,
             "name",
             "description",
             price,
             stock,
             created_at
`

type UpdateProductParams struct {
	ID          int32
	MerchantID  int32
	Name        string
	Description sql.NullString
	Price       float64
	Stock       int32
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.MerchantID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
	)
	return i, err
}
